<div id="accessoriesWrapper">
	<div class="decorative1">
		<a href="/img/accessories/win2.jpg" data-lightbox="roadtrip"><img width="250" height="900" src="/img/accessories/win2.jpg"/></a>
		<p id="contact">Interested? <a id="contact" href="http://mosaic.localhost/contact">Contact us!</a></p>
	</div>
	<div class="decorative2">
		<a href="/img/accessories/win1.jpg" data-lightbox="roadtrip"><img width="650" height="1000" src="/img/accessories/win1.jpg"/></a>
		<p id="contact">Interested? <a id="contact" href="http://mosaic.localhost/contact">Contact us!</a></p>
	</div>
</div>