<div id="catalogueWrapper" class="container">
	<h1 class="page-header">Prototyp katalogu</h1>
	<div id="catalogue" class="col-lg-10"></div>
	<nav id="catalogueMenu" class="col-lg-2">
		<ul class="nav nav-pills nav-stacked span2">
		    <li><a href="#victorian">Victorian</a></li>
		    <li><a href="#">Unglazed?</a></li>
		    <li><a href="#">Glazed?</a></li>
		    <li><a href="#">Anti-slip?</a></li>
		    <li><a href="#">Satin&matt?</a></li>
		    <li><a href="#">Round?</a></li>
		    <li><a href="#">Nie ogarniam</a></li>
		</ul>
	</nav>
</div>