<div id="catalogueWrapper" class="container">
	<h1 class="page-header">Catalogue</h1>
	<nav id="catalogueMenu" class="btn-group">
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Unglazed</button>
    		<ul class="dropdown-menu">
      			<li><a data-category="unglazed_victorian-9mm">Victorian tiles thickness 9 mm</a></li>
      			<li><a data-category="unglazed_tiles3.5x3.5-9mm">Tiles size 3.5x3.5cm thickness 9mm</a></li>
      			<li><a data-category="unglazed_tiles5x5-9mm">Tiles size 5x5cm thickness 9mm</a></li>
      			<li><a data-category="unglazed_tiles7x7-9mm">Tiles size 7x7cm thickness 9mm</a></li>
      			<li><a data-category="unglazed_tiles10x10-9mm">Tiles size 10x10cm thickness 9mm</a></li>
      			<li><a data-category="unglazed_tiles15x15-9mm">Tiles size 15x15cm thickness 9mm</a></li>
      			<li><a data-category="unglazed_octagon10x10-9mm">Octagon 10x10cm thickness 9mm with dots 3.5x3.5cm</a></li>
      			<li><a data-category="unglazed_octagon15x15-9mm">Octagon 15x15cm thickness 9mm with dots 5x5cm</a></li>
      			<li><a data-category="unglazed_hexagon10x10-9mm">Hexagon 10x10cm thickness 9mm</a></li>
      			<li><a data-category="unglazed_basket">Basket weave mix of 2.35x5cm and 1.2x1.2cm tiles</a></li>
      			<li><a data-category="unglazed_tiles1.2x1.2-5mm">Tiles size 1.2x1.2cm thickness 5mm</a></li>
      			<li><a data-category="unglazed_tiles2x2-3.8mm">Tiles size 2x2cm thickness 3.8mm</a></li>
      			<li><a data-category="unglazed_hexagon2.5x2.5-3.8mm">Hexagon 2.5x2.5cm thickness 3.8mm</a></li>
      			<li><a data-category="unglazed_tiles2.35x5-5mm">Tiles size 2.35x5cm thickness 5mm</a></li>
      			<li><a data-category="unglazed_tiles5x5-5mm">Tiles size 5x5cm thickness 5mm</a></li>
      			<li><a data-category="unglazed_hexagon5x5-5mm">Hexagon 5x5cm thickness 5mm</a></li>
    		</ul>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Glazed</button>
    		<ul class="dropdown-menu">
      			<li><a data-category="glazed_tiles2.5x2.5-cmm" href="#">Tiles size 2.5x.2.5 cmm</a></li>
    		</ul>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-category="">Satin&matt</button>
    		<ul class="dropdown-menu">
      			<li><a data-category="satin&matt_tiles2.5x2.5-cmm" href="#">Tiles size 2.5x.2.5 cmm</a></li>
    		</ul>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-category="mosaicdesigns_mosaicdesigns">Mosaic Designs</button>
  		</div>
	</div>
	<div id="catalogue" class="col-lg-12"><?php echo $this->Products; ?></div>
</div>