<div id="catalogueWrapper" class="container">
	<h1 class="page-header">Catalogue</h1>
	<nav id="catalogueMenu" class="btn-group">
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Unglazed</button>
    		<ul class="dropdown-menu">
      			<li><a data-category="unglazed/victorian" href="#">Victorian tiles thickness 9 mm</a></li>
      			<li><a data-category="unglazed/tiles70x70" href="#">Tiles size 70x70cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/tiles50x50" href="#">Tiles size 50x50cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/tiles35x35" href="#">Tiles size 35x35cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/tiles5x5-9mm" href="#">Tiles size 5x5cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/tiles7x7" href="#">Tiles size 7x7cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/tiles10x10" href="#">Tiles size 10x10cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/tiles15x15" href="#">Tiles size 15x15cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/octagon10x10" href="#">Octagon 10x10cm thickness 9mm with dots 3.5x3.5cm</a></li>
      			<li><a data-category="unglazed/octagon15x15" href="#">Octagon 15x15cm thickness 9mm with dots 5x5cm</a></li>
      			<li><a data-category="unglazed/hexagon10x10" href="#">Hexagon 10x10cm thickness 9mm</a></li>
      			<li><a data-category="unglazed/basket" href="#">Basket weave mix of 2.35x5cm and 1.2x1.2cm tiles</a></li>
      			<li><a data-category="unglazed/tiles1.2x1.2" href="#">Tiles size 1.2x1.2cm thickness 5mm</a></li>
      			<li><a data-category="unglazed/tiles2x2" href="#">Tiles size 2x2cm thickness 3.8mm</a></li>
      			<li><a data-category="unglazed/hexagon2.5x2.5" href="#">Hexagon 2.5x2.5cm thickness 3.8mm</a></li>
      			<li><a data-category="unglazed/tiles2.35x5" href="#">Tiles size 2.35x5cm thickness 5mm</a></li>
      			<li><a data-category="unglazed/tiles5x5-5mm" href="#">Tiles size 5x5cm thickness 5mm</a></li>
      			<li><a data-category="unglazed/hexagon5x5" href="#">Hexagon 5x5cm thickness 5mm</a></li>
      			<li><a data-category="unglazed/oldVictorian" href="#">Old Victorian</a></li>
    		</ul>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Glazed</button>
    		<ul class="dropdown-menu">
      			<li><a data-category="glazed/tiles2.5x2.5" href="#">Tiles size 2.5x.2.5 cmm</a></li>
    		</ul>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Anti-slip</button>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-category="">Satin&matt</button>
    		<ul class="dropdown-menu">
      			<li><a data-category="satin&matt/tiles2.5x2.5" href="#">Tiles size 2.5x.2.5 cmm</a></li>
    		</ul>
  		</div>
		<div class="btn-group">
    		<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Round</button>
  		</div>
	</div>
	<div id="catalogue" class="col-lg-12"></div>
</div>
