<div class='col-lg-3'></div>
<?php 
    echo $this->bootstrapForm($ContactForm);
?>
<div id='contactWrapper' class='col-lg-4'>
    <div class='col-lg-1'></div>
    
    <div class='col-lg-8'>Contact information<br>
        <br>
        Unit 5008<br>
        67 Gap Road <br>
        SW19 8JA<br>
        London, England  <br>
        <br>
        Tel: 0800 211 8776 (free)<br>
        Mob: 00 44 7823 821 379<br>
        <a href="mailto:info@martinmosaic.com">info@martinmosaic.com</a><br>
    </div>
    <div class='col-lg-2'></div>
</div>
<div class='clearfix'></div>
<div id="mapCanvas" class='col-lg-6'></div>