<div id="creatorWrapper">
    <div id="creatorToolbar">
        <input id="paintColor" type="color" name="paintColor">
        <input id="lineSize" type="number" name="lineSize" min="1" max="100" value="1">
        <div id="brush" class="selected"></div>
        <div id="drawLine">Line</div>
        <div id="strokeRect"></div>
        <div id="fillRect"></div>
        <div id="strokeCirc"></div>
        <div id="fillCirc"></div>
    </div>
    <canvas id="creatorCanvas" class="defaultCursor NoSelect" width="500" height="500"></canvas>
</div>