<div id="board">
	<div id='slideshowHolder'>
 		<img src='/img/test/test1.jpg' alt='img1' />
 		<img src='/img/test/test2.jpg' alt='img2' />
 		<img src='img/test/test3.png' alt='img3' />
 		<img src='img/test/test4.png' alt='img4' />
 		<img src='img/test/test5.png' alt='img5' />
	</div>
</div>
<fieldset>
		<div id="hometext">
			<p><b id="hometext">MartinMosaic</b> is a company specializing in designing and making bespoke  mosaic tiles. </p>
	 		<p>Our tiles can be used both internally and externally.</br> Recent projects have included hallways, floors and walls in restaurants, kitchens, bathrooms, night clubs, shops, front gardens and swimming pools. </p>
			<p>We pride ourselves in meeting all our customers’ needs by listening and responding to their requirements so that they receive an individual, unique and personal product. </p>
			<p>Our experience and craftsmanship allows us to work to an extremely high level of workmanship at competitive prices.</p>
		</div>
</fieldset>