<div id="board">
	<div id='slideshowHolder'>
 		<img src='/img/home/image1.png'/>
 		<img src='/img/home/image2.png'/>
 		<img src='img/home/image3.png'/>
 		<img src='img/home/image4.png'/>
	</div>
	<ul id="infocontact">
		<li><img src="/img/home/c1.png" / title="00 44 78 238 821 379"> 00 44 7823 821 379</li>
		<li><img src="/img/home/c2.png"><a href="mailto:info@martinmosaic.com" style="color:black;"> info@martinmosaic.com </a></li>
	</ul>
</div>
<fieldset>
		<div id="hometext">
			<p><b id="hometext">MartinMosaic</b> is a company specializing in designing and making bespoke  mosaic tiles. </p>
	 		<p>Our tiles can be used both internally and externally.</br> Recent projects have included hallways, floors and walls in restaurants, kitchens, bathrooms, night clubs, shops, front Victorian pathway and swimming pools. </p>
			<p>We pride ourselves in meeting all our customers’ needs by listening and responding to their requirements so that they receive an individual, unique and personal product. </p>
			<p>Our experience and craftsmanship allows us to work to an extremely high level of workmanship at competitive prices.</p>
		</div>
</fieldset>
