<div id="accessoriesWrapper">
	<div class="decorative1">
		<a href="/img/accessories/win2.jpg" class="pullup"><img width="250" height="900" src="/img/accessories/win2.jpg"/></a>
		<p class="contact">Interested? <a href="/contact">Contact us!</a></p>
	</div>
	<div class="decorative2">
		<a href="/img/accessories/win1.jpg" class="pullup"><img width="650" height="1000" src="/img/accessories/win1.jpg"/></a>
		<p class="contact">Interested? <a href="/contact">Contact us!</a></p>
	</div>
</div>

<div id="technicalWrapper">
	<p class="briare">Briare technical:</p>
	<div class="briare">
		<a href="/img/technical/technical5.jpg" class="pullup"><img width="300" height="300" src="/img/technical/technical5.jpg"/></a>
		<a href="/img/technical/technical6.jpg" class="pullup"><img width="300" height="300" src="/img/technical/technical6.jpg"/></a>
	</div>
	<p class="winckelmans">Winckelmans technical:</p>
	<div class="winckelmans">
		<a href="/img/technical/technical1.jpg" class="pullup"><img width="265" height="265" src="/img/technical/technical1.jpg"/></a>
		<a href="/img/technical/technical2.jpg" class="pullup"><img width="265" height="265" src="/img/technical/technical2.jpg"/></a>
		<a href="/img/technical/technical3.jpg" class="pullup"><img width="265" height="265" src="/img/technical/technical3.jpg"/></a>
		<a href="/img/technical/technical4.jpg" class="pullup"><img width="265" height="265" src="/img/technical/technical4.jpg"/></a>
		<a href="/img/technical/winckelmans.jpg" class="pullup"><img width="265" height="265" src="/img/technical/winckelmans.jpg" /></a>
	</div>
</div>

<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Martin
Mosaic</B></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">
sells products online.  We offer a wide selection of quality mosaic
materials at hard to beat prices. </FONT></FONT><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">Mosaic
Tiles are beautiful and timeless. They can be used in numerous
applications and we have a huge range of Mosaic and Tiles available
online. </FONT></FONT></FONT>
</P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
<FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">All
of our Mosaic Tiles come in different sheet sizes; you will find the
sheet size listed next to each product. Traditionally mosaic tiles
were sold only by the SqM but we realized there was a gap in the
market and people wanted to buy mosaic and tiles in smaller
quantities for features and mosaic art. We  provide hand cut tiles
for different sizes 1cm, 2cm etc</FONT></FONT></FONT></P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
<FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Important</B></FONT></FONT></FONT><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">;
please note that temporary we do not have a stock. </FONT></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">The
length of waiting time of your order takes from 1 to 3 weeks. </FONT></FONT>
</P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 100%">
<FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">If
you have any questions about tile sizes or tile sheet sizing please
contact us on  </FONT></FONT></FONT><A HREF="mailto:info@martinmosaic.com"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">info@martinmosaic.com</FONT></FONT></A><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">
or by calling us </FONT></FONT></FONT><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>00
44 7823 821 379</B></FONT></FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.14in"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Payment
information</B></FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">All
orders are shipped only after we have received full payment.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">Currently
we accept the following payment methods to pay at on-line Martin
Mosaic:</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%">•    <FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">We
accept payment via BACS bank transfer, card or cheque</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%">•    <FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">PayPal.
Please note that some banks and credit cards charge conversion fees
for PayPal  payments these are beyond our control.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in">•    <FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">Pay
at pick up</FONT></FONT></P>
<UL>
	<LI><P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
	<FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">A
	pro forma invoice will be raised and sent via email. Once
	notification of payment is received we issue an invoice for your
	records and begin the final drawings (where applicable).</FONT></FONT></P>
</UL>
<P STYLE="margin-bottom: 0.14in"><BR><BR>
</P>
<P STYLE="margin-bottom: 0.14in"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Shipping
and </B></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Delivery
Damages</B></FONT></FONT></P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.05in; line-height: 150%">
<FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Shipping</B></FONT></FONT></P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
<FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">Your
tiles are assembled, boxed and stored and ready for collection or
delivery.</FONT></FONT></P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
<FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">All
of our tiles are delivered by a courier company. We try to ship
within 72 hours after payment is received. </FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">We
deliver most items</SPAN></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">&nbsp;</SPAN></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B><SPAN STYLE="">Monday
to Saturday, 7.30am-6pm</SPAN></B></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">&nbsp;</SPAN></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">(although
some of our carriers may deliver slightly earlier or later)</SPAN></FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">The
length of time your order takes to varies according to your location.
Within the United Kingdom normally delivers within 5 working days.
Outside the UK it might take up to 2 - 3 weeks. </FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN LANG="en-US">We
will not leave products on public property.</SPAN></FONT></FONT><FONT COLOR="#393535"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN LANG="en-US">
 </SPAN></FONT></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">All
orders will need to be signed for on delivery unless arrangements
have been made prior to delivery.</FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">
Someone will need to be present at the time of delivery to accept and
sign for the goods as a failed delivery may result in you incurring a
re-delivery charge.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">Delivery
is by courier and the price will vary according to the weight. </FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">We
offer the following delivery options depending on the size of the
order. One square metre of tiles have a weight of approximately 20kg.</FONT></FONT></P>
<UL>
	<LI><P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
	<FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">Standard
	2- 3 Day Delivery by currier  for orders up to;</FONT></FONT></P>
	<LI><P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
	<FONT COLOR="#000c12"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">Parcel
	Delivery up to 20 KG – cost </SPAN></FONT></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">£20.00</FONT></FONT></P>
	<LI><P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 150%">
	<FONT COLOR="#000c12"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">Pallet
	Deliver 40 KG – cost </SPAN></FONT></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">£35.00</FONT></FONT></P>
</UL>
<P STYLE="margin-bottom: 0.14in"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">If
you find delivery cheaper elsewhere let us know and we will try and
beat it!</FONT></FONT></P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 100%">
<FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">If
you require a delivery to a Non Mainland UK address, please contact
us, prior to placing your order.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Delivery
Damages</B></FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">If
your purchase is damaged in transit we will send you a &quot;no
charge&quot; replacement, freight free. You will need to return the
damaged product (or fragments which demonstrate reasonable evidence
of breakage in the case of international orders) to us for
assessment.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">It
is extremely important that you indicate the damages on the delivery
note when you sign for the goods. You must notify Martin Mosaic by
calling </FONT></FONT><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>00
44 7823 821 379 </B></FONT></FONT></FONT><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">i</FONT></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">f
there are any damages or irregularities to your order within 24 hours
of delivery.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B><SPAN STYLE="">MartinMosaic</SPAN></B></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><SPAN STYLE="">
will aim to replace faulty goods within 2 working days of you
notifying us.</SPAN></FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">The
majority of goods reach the destination undamaged; however, damages
during transit do occur. Please ensure that you've allowed extra time
for your order to arrive in the case that damages occur. Martin
Mosaic cannot be held responsible for extra costs incurred by the
goods being delayed.</FONT></FONT></P>
<P STYLE="margin-bottom: 0.14in; line-height: 150%"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">We
always try to meet our customers' requirements so if you have a
special need, please call us on </FONT></FONT><FONT COLOR="#000000"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>00
44 7823 821 379 </B></FONT></FONT></FONT><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt">and
we will do our best to accommodate you.</FONT></FONT></P>
<P STYLE="margin-top: 0.02in; margin-bottom: 0.02in; line-height: 100%">
<BR><BR>
</P>
<P STYLE="margin-bottom: 0.14in"><FONT COLOR="gold"><FONT FACE="Verdana, serif"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Martin Mosaic 2014 all rights reserved.</B></FONT></FONT></FONT></P>
