<fieldset>
		<div id="infotxt">
			<p>Martin Mosaic is online shop. We offers a wide selection of quality mosaic materials at hard to beat prices.</p> 

			<p>Tel: +44 7471015360</p>
						
			<p>VAT Registration: ?????????</p>
			
			<p>Payment information</p>
			
			<p>All orders are shipped only after we have received full payment.<br/>
				Currently we accept the following payment methods to pay at online Martin Mosaic:<br/>
			<ul>	
				<li>PayPal. Please note that some banks and credit cards charge conversion fees for PayPal payments these are beyond our control.</li>
				<li>Pay at pick up</li>
				<li>Debit or Credit card</li>
				<li>Wire Transfers:</li>
			</ul>
			<p>Swift Code: </p>
			<p>Acct Number: </p>
			<p>Account Holder: Martin Mosaic </p>
			<p>Our Bank Name:</p></p>
			
			
			<p>Shipping and Return Information</p>
			
			<p>Shipping</p>
			
			<p>All of our tiles are delivered by a courier company. We try to ship within 72 hours (Mon-Fri) after payment is received. 
			The length of time your order takes to varies according to your location. Within the United Kingdom normally delivers within 5 working days. Outside the UK it might take up to 2 - 3 weeks.
			All orders will need to be signed for on delivery unless arrangements have been made prior to delivery. 
			If we are unable to acquire a signature, your order will be returned and a second delivery date will need to be arranged.</p>
			
			<p>Goods damaged in transit</p>
			
			<p>If your purchase is damaged in transit we will send you a "no charge" replacement, freight free. You will need to return the damaged product (or fragments which demonstrate reasonable evidence of breakage in the case of international orders) to us for assessment.</p>
			
			<p>Returns</p>
			<p>If you are not totally satisfied with your order for any reason merchandise will be accepted for return within 14 days of purchase. Merchandise must be unused and in new condition. 
			You are responsible for all the shipping costs of the order (to you and from you). 
			You must contact us by phone ( 00 44 747 101 53 60 ) or email us for authorization and instructions before returning any item.</p>


		</div>
</fieldset>