<div id="productWrapper">
	<div id="productPicture" class="col-lg-8">
		<img src="<?php echo $Product->getPath(); ?>"/>
	</div>
	<div id="rightWrapper" class="col-lg-4">
		<div id='productDetails' class='col-lg-12'><?php echo $Product->getProductDetails(); ?></div>
		<div id='addToCartFormWrapper'><?php echo $this->renderAddToCartForm($AddToCartForm);?></div>
		<div class='zapychacz col-lg-2'></div><a id='backButton' class='btn btn-primary col-lg-8' href="/catalogue/<?php echo $Product->getCategory(); ?>" type="button" class="btn btn-default">Back to catalogue</a>
	</div>
</div>  