<p id="text">Winckelmans technical:</p>
<div id="technical">
	<a href="/img/technical/technical1.jpg" data-lightbox="roadtrip"><img width="300" height="300" src="/img/technical/technical1.jpg"/></a>
	<a href="/img/technical/technical2.jpg" data-lightbox="roadtrip"><img width="300" height="300" src="/img/technical/technical2.jpg"/></a>
	<a href="/img/technical/technical3.jpg" data-lightbox="roadtrip"><img width="300" height="300" src="/img/technical/technical3.jpg"/></a>
	<a href="/img/technical/technical4.jpg" data-lightbox="roadtrip"><img width="300" height="300" src="/img/technical/technical4.jpg"/></a>
</div>
<p id="text">Briare technical:</p>
<div id="technical">
	<a href="/img/technical/technical5.jpg" data-lightbox="roadtrip"><img width="300" height="300" src="/img/technical/technical5.jpg"/></a>
	<a href="/img/technical/technical6.jpg" data-lightbox="roadtrip"><img width="300" height="300" src="/img/technical/technical6.jpg"/></a>
</div>