<p>Winckelmans technical:</p>
<div id="technical">
	<a id="dziala" href="/img/technical/technical1.jpg" data-lightbox="roadtrip"><img src="/img/technical/technical1s.jpg"/></a>
	<a href="/img/technical/technical2.jpg" data-lightbox="roadtrip"><img src="/img/technical/technical2s.jpg"/></a>
	<a href="/img/technical/technical3.jpg" data-lightbox="roadtrip"><img src="/img/technical/technical3s.jpg"/></a>
	<a href="/img/technical/technical4.jpg" data-lightbox="roadtrip"><img src="/img/technical/technical4s.jpg"/></a>
</div>