<!DOCTYPE html>
<html lang="en">
    <head>
        <!--Encoding and content type===========================================-->
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <!--Title, description, SEO meta tags===================================-->
        <title><?php echo $this->Title; ?></title>
        <meta name="robots" content="index, follow"/>
        <meta name="description" content="<?php // TODO ?>"/>
        <meta name="keywords" content="<?php // TODO ?>"/>
        <link rel="canonical" href="<?php echo isset($this->CanonicalURL) ? $this->CanonicalURL : $this->serverUrl(true); ?>"/>
        <!--Icon and other dependencies==========================================-->
        <?php //TODO ?>
        <!-- CSS libs===========================================================-->
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/js/lib/fancybox/source/jquery.fancybox.css" type="text/css" media="screen"/>
        <!--Own CSS=============================================================-->
        <link rel="stylesheet" type="text/css" href="/css/general/Mosaic.css"/>
        <!--JS libs=========================================================-->
        <script type="text/javascript" src="/js/lib/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/lib/fancybox/source/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="/js/lib/jqFancyTransitions.1.8.min.js"></script>
		<script type="text/javascript" src="/js/lib/jquery.validate.min.js"></script>
        <!--3rd party JS=========================================================-->
        <?php //TODO ?>
        <!--Own JS===========================================================-->
        <?php
            // If an array with per page scripts was provided, attach them.
            if(is_array($this->Scripts))
            {
                foreach($Scripts as $Script)
                {
                    echo "<script type='text/javascript' src='$Script'></script>";
                }
            }
            // If an array with per page styles was provided, attach them.
            if(is_array($this->Styles))
            {
                foreach($Styles as $Style)
                {
					echo "<link rel='stylesheet' type='text/css' href='$Style'/>";
				}
			}
        ?>
    </head>
    <body>
        <header id="siteHeader" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <img id="logo" class='col-lg-3' src="/img/logos/logo.png" alt="Martin Mosaic"/>
                <ul class="nav navbar-nav col-lg-9">
                    <li class="menu"><a href="<?php echo $this->url('mosaic', ['action' => 'home']); ?>">Home</a></li>
                    <li class="menu"><a href="<?php echo $this->url('mosaic', ['action' => 'catalogue']); ?>">Catalogue</a></li>
                    <li class="menu btn-group technical">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Technical</a>
						<ul class="dropdown-menu">
				  			<li><a href="/technical/winckelmans">Winckelmans</a></li>
				  			<li><a href="/technical/briare">Briare</a></li>
						</ul>
					</li>
                    <li class="menu specialoffers"><a href="<?php echo $this->url('mosaic', ['action' => 'specialoffers']); ?>">Special offers</a></li>
                    <li class="menu"><a href="<?php echo $this->url('mosaic', ['action' => 'information']); ?>">Information</a></li>
                    <li class="menu btn-group accessories">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Accessories</a>
						<ul class="dropdown-menu">
				  			<li><a href="/accessories/decorative1">Decorative Tiles 5x5cm</a></li>
				  			<li><a href="/accessories/decorative2">Decorative Tiles 10x10cm</a></li>
						</ul>
					</li>
                    <li class="menu"><a href="<?php echo $this->url('mosaic', ['action' => 'contact']); ?>">Contact</a></li>
                    <?php
	                    if(!isset($_SESSION['User']))
						{
					?>
                    <li class="menu"><a href="<?php echo $this->url('user', ['action' => 'signin']); ?>">Sign in</a></li>
                    <?php
						}
                    	else
                    	{
                    		$this->renderUserPanel();
						}
					?>
                </ul>
            </div>
        </header>
        <div id="content" class="col-lg-12">
            <?php echo $this->content; ?>
        </div>
        <footer id="siteFooter"></footer>
	    <script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
			ga('create', 'UA-53768216-1', 'auto');
			ga('send', 'pageview');
		</script>
    </body>
</html>