UPDATE Products SET Price = 76, Description = 'Basket weave -White-Super white and black dots 23x50 dots 1.2x1.2 - thickness 5mm. Perfect for floors.' WHERE ProductName = 'SP-01';
UPDATE Products SET Price = 58, Description = 'Checkerboard white and black tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-02';
UPDATE Products SET Price = 65, Description = 'White and black tiles size 5cm x 5cm thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-03';
UPDATE Products SET Price = 97, Description = 'Checkerboard white and black tiles size 10cm x 10cm - thickness 9mm. Sheets size 3 tiles by 3 tiles.' WHERE ProductName = 'SP-04';
UPDATE Products SET Price = 87, Description = 'Checkerboard white and black tiles size 10cm x 10cm - thickness 9mm. Sheets size 3 tiles by 3 tiles.' WHERE ProductName = 'SP-05';
UPDATE Products SET Price = 97, Description = 'Checkerboard white and black tiles size 10cm x 10cm - thickness 9mm. Sheets size 3 tiles by 3 tiles.' WHERE ProductName = 'SP-06';
UPDATE Products SET Price = 97, Description = 'Checkerboard white and black tiles size 10cm x 10cm - thickness 9mm. Sheets size 3 tiles by 3 tiles.' WHERE ProductName = 'SP-07';
UPDATE Products SET Price = 37, Description = 'Checkerboard black and red tiles size 2cm by 2cm thickness 4mm. Sheets size 14 tiles by 14 tiles. Perfect for floors and walls.' WHERE ProductName = 'SP-08';
UPDATE Products SET Price = 37, Description = 'Checkerboard white and black tiles size 2cm by 2cm thickness 4mm. Sheets size 14 tiles by 14 tiles . Perfect for floors and walls.' WHERE ProductName = 'SP-09';
UPDATE Products SET Price = 125, Description = 'I am selling checkerboard white and black tiles size 5cm x 5cm - thickness 9mmm. Sheets size 6 tiles buy 6 tiles or we can sell loose tiles. Loose tile 125 £ only sm2. Assemblers 150 £ only sm2 sheets size 6 tiles by 6 tiles. Possible joint 1mm,2 or 3mm.' WHERE ProductName = 'SP-10';
UPDATE Products SET Price = 64, Description = 'White and black tiles 100x100-thickness 9mm. Sheets size 3 tiles by 3 tiles or we can sell loose tiles. Loose tiles £ 64 sqm. Assemblers checkeborad £ 84 sqm ,Possible joint 2 or 3 mm. ' WHERE ProductName = 'SP-11';
UPDATE Products SET Price = 75, Description = 'White and black design tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-12';
UPDATE Products SET Price = 70, Description = 'White and black design tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-13';
UPDATE Products SET Price = 70, Description = 'White and black design tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-14';
UPDATE Products SET Price = 70, Description = 'White and black design tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-15';
UPDATE Products SET Price = 37, Description = 'Checkerboard white and red tiles size 2cm by 2cm thickness 4mm.Sheets size 14 tiles by 14 tiles. Perfect for floors and walls.' WHERE ProductName = 'SP-16';
UPDATE Products SET Price = 60, Description = 'Checkerboard black and red tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles.' WHERE ProductName = 'SP-17';
UPDATE Products SET Price = 60, Description = 'Checkerboard white and red tiles size 5cm x 5cm - thickness 5mm. Sheets size 6 tiles by 6 tiles. ' WHERE ProductName = 'SP-18';
UPDATE Products SET Price = 50, Description = 'Gloss mosaic Tiles for kitchen,floors,walls or bathroom.Over 1.5 sqm ,size sheets 11x11 tiles joint 2mm. Product from BRIARE Harmonie ASTER.' WHERE ProductName = 'SP-19';
